exclude: '.*\.ipynb$'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-yaml
    args: ['--unsafe']
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
    additional_dependencies:
      - tomli
    exclude: 'cassettes/'

- repo: https://github.com/markdownlint/markdownlint
  rev: v0.13.0
  hooks:
    - id: markdownlint
      args:
        - --rule
        - "MD033:allowed_elements=img"

- repo: local
  hooks:
  - id: lint
    name: lint
    entry: make lint
    types: [python]
    language: system
    pass_filenames: false
