name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Describe the feature
      description: What would you like to see added or changed?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use case
      description: Why do you need this feature? What problem does it solve?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed solution
      description: How do you think this should work? (optional)
