name: 'Setup uv'
description: 'Install and configure uv'

inputs:
  enable-cache:
    description: 'Enable uv caching'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: ${{ inputs.enable-cache }}
